### ISSUE TITLE
Use older version of glibc for Linux version

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/FreeImage#10]
After upgrading Resonite to the latest Linux version compiled by the Github Actions, some Linux users are having issues loading the library on their systems, which seems to be due to a newer version of glibc being required.

Lowering the version could help improve compatibility.

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1241

**Comment by Nutcake** [comment]
I recommend at maximum using GLIBCXX_3.4.25, since many people run the Resonite headless using the [mono](https://hub.docker.com/_/mono) image, which is based on Debian 10 and hence limited to that version.

**Comment by Frooxius** [comment]
If you (or anyone else) is interested, you can also poke at the GitHub Actions and open a PR to change it to that version. We'll tackle it otherwise.

**Comment by Nutcake** [comment]
I'll look into it.
