### ISSUE TITLE
Description of difference

### ISSUE THREAD

**Issue by sirkitree** [Yellow-Dog-Man/FreeImage#6]
Could the difference between this fork and the official library be listed in the README? A bullet list of major differences would be great. Are there any changes that are being considered for contribution back to the main project? If so links to those issues would also be nice to see listed here.

**Comment by ProbablePrime** [comment]
There's a list now in the readme.

I checked most of the freeimage website but it doesnt seem like it has been updated. The project has a confusing setup and I found it difficult to find the code's source repository so I might be wrong.
