### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/FreeImage#7]
Resonite has some reported performance concerns here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/874

We should investigate them.

**Comment by Nutcake** [comment]
I did some local testing and recompiled FreeImage with this line here:
 https://github.com/Yellow-Dog-Man/FreeImage/blob/72e49dbbaab41db9d651317b813cd4939793c217/Source/FreeImage/PluginWebP.cpp#L475 set to zero instead:
`config.method = 0;`

This change reduced the average time it takes between pressing the screenshot button and steam registering the screenshot from about 7 seconds to less than 2 seconds. The resulting screenshots show no difference in quality to my eye:
[method = 0](https://cdn.protogen.zip/-LEKhCSAeVo/method0.webp)
[method = 6](https://cdn.protogen.zip/-h8DTJxACbp/method6.webp)
(test image from here https://imagecompression.info/test_images/)

Now I don't know if this has secondary effects elsewhere, it's possible it could reduce the quality of the image shown in-game? However from just a visual inspection that seems unchanged as well.
